<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductPictureSeeder extends Seeder
{

    private $productsPictures =[
        ['product_id' => 1, 'picture_id' => 1],
        ['product_id' => 1, 'picture_id' => 2],
        ['product_id' => 2, 'picture_id' => 3],
        ['product_id' => 2, 'picture_id' => 4],
        ['product_id' => 3, 'picture_id' => 5],
        ['product_id' => 3, 'picture_id' => 6],
        ['product_id' => 4, 'picture_id' => 7],
        ['product_id' => 4, 'picture_id' => 8],
        ['product_id' => 5, 'picture_id' => 9],
        ['product_id' => 5, 'picture_id' => 10],
        ['product_id' => 6, 'picture_id' => 11],
        ['product_id' => 6, 'picture_id' => 12],
        ['product_id' => 7, 'picture_id' => 13],
        ['product_id' => 7, 'picture_id' => 14],
        ['product_id' => 8, 'picture_id' => 15],
        ['product_id' => 8, 'picture_id' => 16],
        ['product_id' => 9, 'picture_id' => 17],
        ['product_id' => 9, 'picture_id' => 18],
        ['product_id' => 10, 'picture_id' => 19],
        ['product_id' => 10, 'picture_id' => 20],
        ['product_id' => 11, 'picture_id' => 21],
        ['product_id' => 11, 'picture_id' => 22],
        ['product_id' => 12, 'picture_id' => 23],
        ['product_id' => 12, 'picture_id' => 24],
        ['product_id' => 13, 'picture_id' => 25],
        ['product_id' => 13, 'picture_id' => 26],
        ['product_id' => 14, 'picture_id' => 27],
        ['product_id' => 14, 'picture_id' => 28],
        ['product_id' => 15, 'picture_id' => 29],
        ['product_id' => 15, 'picture_id' => 30],
        ['product_id' => 16, 'picture_id' => 31],
        ['product_id' => 16, 'picture_id' => 32],
        ['product_id' => 17, 'picture_id' => 33],
        ['product_id' => 17, 'picture_id' => 34],
        ['product_id' => 18, 'picture_id' => 35],
        ['product_id' => 18, 'picture_id' => 36],
        ['product_id' => 19, 'picture_id' => 37],
        ['product_id' => 19, 'picture_id' => 38],
        ['product_id' => 20, 'picture_id' => 39],
        ['product_id' => 20, 'picture_id' => 40],
        ['product_id' => 21, 'picture_id' => 41],
        ['product_id' => 21, 'picture_id' => 42],
        ['product_id' => 22, 'picture_id' => 43],
        ['product_id' => 22, 'picture_id' => 44],
        ['product_id' => 23, 'picture_id' => 45],
        ['product_id' => 23, 'picture_id' => 46],
        ['product_id' => 24, 'picture_id' => 47],
        ['product_id' => 24, 'picture_id' => 48],
        ['product_id' => 25, 'picture_id' => 49],
        ['product_id' => 25, 'picture_id' => 50],
        ['product_id' => 26, 'picture_id' => 51],
        ['product_id' => 26, 'picture_id' => 52],
        ['product_id' => 27, 'picture_id' => 53],
        ['product_id' => 27, 'picture_id' => 54],
        ['product_id' => 28, 'picture_id' => 55],
        ['product_id' => 28, 'picture_id' => 56],
        ['product_id' => 29, 'picture_id' => 57],
        ['product_id' => 29, 'picture_id' => 58],
        ['product_id' => 30, 'picture_id' => 59],
        ['product_id' => 30, 'picture_id' => 60],
        ['product_id' => 31, 'picture_id' => 61],
        ['product_id' => 31, 'picture_id' => 62],
        ['product_id' => 32, 'picture_id' => 63],
        ['product_id' => 32, 'picture_id' => 64],
        ['product_id' => 33, 'picture_id' => 65],
        ['product_id' => 33, 'picture_id' => 66],
        ['product_id' => 34, 'picture_id' => 67],
        ['product_id' => 34, 'picture_id' => 68],
        ['product_id' => 35, 'picture_id' => 69],
        ['product_id' => 35, 'picture_id' => 70],
        ['product_id' => 36, 'picture_id' => 71],
        ['product_id' => 36, 'picture_id' => 72],
        ['product_id' => 37, 'picture_id' => 73],
        ['product_id' => 37, 'picture_id' => 74],
        ['product_id' => 38, 'picture_id' => 75],
        ['product_id' => 38, 'picture_id' => 76],
        ['product_id' => 39, 'picture_id' => 77],
        ['product_id' => 39, 'picture_id' => 78],
        ['product_id' => 40, 'picture_id' => 79],
        ['product_id' => 40, 'picture_id' => 80],
        ['product_id' => 41, 'picture_id' => 81],
        ['product_id' => 41, 'picture_id' => 82],
        ['product_id' => 42, 'picture_id' => 83],
        ['product_id' => 42, 'picture_id' => 84],
        ['product_id' => 43, 'picture_id' => 85],
        ['product_id' => 43, 'picture_id' => 86],
        ['product_id' => 44, 'picture_id' => 87],
        ['product_id' => 44, 'picture_id' => 88],
        ['product_id' => 45, 'picture_id' => 89],
        ['product_id' => 45, 'picture_id' => 90],
        ['product_id' => 46, 'picture_id' => 91],
        ['product_id' => 46, 'picture_id' => 92],
        ['product_id' => 47, 'picture_id' => 93],
        ['product_id' => 47, 'picture_id' => 94],
        ['product_id' => 48, 'picture_id' => 95],
        ['product_id' => 48, 'picture_id' => 96],
        ['product_id' => 49, 'picture_id' => 97],
        ['product_id' => 49, 'picture_id' => 98],
        ['product_id' => 50, 'picture_id' => 99],
        ['product_id' => 50, 'picture_id' => 101],
        ['product_id' => 51, 'picture_id' => 102],
        ['product_id' => 51, 'picture_id' => 103],
        ['product_id' => 52, 'picture_id' => 104],
        ['product_id' => 52, 'picture_id' => 105],
        ['product_id' => 53, 'picture_id' => 106],
        ['product_id' => 53, 'picture_id' => 107],
        ['product_id' => 54, 'picture_id' => 108],
        ['product_id' => 54, 'picture_id' => 109],
        ['product_id' => 55, 'picture_id' => 110],
        ['product_id' => 55, 'picture_id' => 111],
        ['product_id' => 56, 'picture_id' => 112],
        ['product_id' => 56, 'picture_id' => 113],
        ['product_id' => 57, 'picture_id' => 114],
        ['product_id' => 57, 'picture_id' => 115],
        ['product_id' => 58, 'picture_id' => 116],
        ['product_id' => 58, 'picture_id' => 117],
        ['product_id' => 59, 'picture_id' => 118],
        ['product_id' => 59, 'picture_id' => 119],
        ['product_id' => 60, 'picture_id' => 120],
        ['product_id' => 60, 'picture_id' => 121],
        ['product_id' => 61, 'picture_id' => 122],
        ['product_id' => 61, 'picture_id' => 123],
        ['product_id' => 62, 'picture_id' => 124],
        ['product_id' => 62, 'picture_id' => 125],
        ['product_id' => 63, 'picture_id' => 126],
        ['product_id' => 63, 'picture_id' => 127],
        ['product_id' => 64, 'picture_id' => 128],
        ['product_id' => 64, 'picture_id' => 129],
        ['product_id' => 65, 'picture_id' => 130],
        ['product_id' => 65, 'picture_id' => 131],
        ['product_id' => 66, 'picture_id' => 132],
        ['product_id' => 66, 'picture_id' => 133],
        ['product_id' => 67, 'picture_id' => 134],
        ['product_id' => 67, 'picture_id' => 135],
        ['product_id' => 68, 'picture_id' => 136],
        ['product_id' => 68, 'picture_id' => 137],
        ['product_id' => 69, 'picture_id' => 138],
        ['product_id' => 69, 'picture_id' => 139],
        ['product_id' => 70, 'picture_id' => 140],
        ['product_id' => 70, 'picture_id' => 141],
        ['product_id' => 71, 'picture_id' => 142],
        ['product_id' => 71, 'picture_id' => 143],
        ['product_id' => 72, 'picture_id' => 144],
        ['product_id' => 72, 'picture_id' => 145],
        ['product_id' => 73, 'picture_id' => 146],
        ['product_id' => 73, 'picture_id' => 147],
        ['product_id' => 74, 'picture_id' => 148],
        ['product_id' => 74, 'picture_id' => 149],
        ['product_id' => 75, 'picture_id' => 150],
        ['product_id' => 75, 'picture_id' => 151],
        ['product_id' => 76, 'picture_id' => 152],
        ['product_id' => 76, 'picture_id' => 153],
        ['product_id' => 77, 'picture_id' => 154],
        ['product_id' => 77, 'picture_id' => 155],
        ['product_id' => 78, 'picture_id' => 156],
        ['product_id' => 78, 'picture_id' => 157],
        ['product_id' => 79, 'picture_id' => 158],
        ['product_id' => 79, 'picture_id' => 159],
        ['product_id' => 80, 'picture_id' => 160],
        ['product_id' => 80, 'picture_id' => 161],
        ['product_id' => 81, 'picture_id' => 162],
        ['product_id' => 81, 'picture_id' => 163],
        ['product_id' => 82, 'picture_id' => 164],
        ['product_id' => 82, 'picture_id' => 165],
        ['product_id' => 83, 'picture_id' => 166],
        ['product_id' => 83, 'picture_id' => 167],
        ['product_id' => 84, 'picture_id' => 168],
        ['product_id' => 84, 'picture_id' => 169],
        ['product_id' => 85, 'picture_id' => 170],
        ['product_id' => 85, 'picture_id' => 171],
        ['product_id' => 86, 'picture_id' => 172],
        ['product_id' => 86, 'picture_id' => 173],
        ['product_id' => 87, 'picture_id' => 174],
        ['product_id' => 87, 'picture_id' => 175],
        ['product_id' => 88, 'picture_id' => 176],
        ['product_id' => 88, 'picture_id' => 177],
        ['product_id' => 89, 'picture_id' => 178],
        ['product_id' => 89, 'picture_id' => 179],
        ['product_id' => 90, 'picture_id' => 180],
        ['product_id' => 90, 'picture_id' => 181],
        ['product_id' => 91, 'picture_id' => 182],
        ['product_id' => 91, 'picture_id' => 183],
        ['product_id' => 92, 'picture_id' => 184],
        ['product_id' => 92, 'picture_id' => 185],
        ['product_id' => 93, 'picture_id' => 186],
        ['product_id' => 93, 'picture_id' => 187],
        ['product_id' => 94, 'picture_id' => 188],
        ['product_id' => 94, 'picture_id' => 189],
        ['product_id' => 95, 'picture_id' => 190],
        ['product_id' => 95, 'picture_id' => 191],
        ['product_id' => 96, 'picture_id' => 192],
        ['product_id' => 96, 'picture_id' => 193],
        ['product_id' => 97, 'picture_id' => 194],
        ['product_id' => 97, 'picture_id' => 195],
        ['product_id' => 98, 'picture_id' => 196],
        ['product_id' => 98, 'picture_id' => 197],
        ['product_id' => 99, 'picture_id' => 198],
        ['product_id' => 99, 'picture_id' => 199],
        ['product_id' => 100, 'picture_id' => 200],
        ['product_id' => 100, 'picture_id' => 201],
        ['product_id' => 101, 'picture_id' => 202],
        ['product_id' => 101, 'picture_id' => 203],
        ['product_id' => 102, 'picture_id' => 204],
        ['product_id' => 102, 'picture_id' => 205],
        ['product_id' => 103, 'picture_id' => 206],
        ['product_id' => 103, 'picture_id' => 207],


    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->productsPictures as $productPicture){
            DB::table('products_pictures')->insert($productPicture);
        }
    }
}
